server:
  port: 8080
spring:
  profiles:
    group:
      default: clients
      test: clients-test
      staging: clients-staging
      prod: clients-prod
  mvc:
    static-path-pattern: /test/**
  main:
    banner-mode: off
  r2dbc:
    writer:
      driver: pool
      protocol: mysql
      host: localhost
      port: 33061
      user: serverdriven
      password: serverdriven
      database: serverdriven_test
    reader:
      driver: pool
      protocol: mysql
      host: localhost
      port: 33061
      user: serverdriven
      password: serverdriven
      database: serverdriven_test
  data:
    redis:
      host: localhost
      port: 63792
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mysql://localhost:33061/serverdriven_test?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    user: serverdriven
    password: serverdriven
    locations: classpath:db/migration
logging:
  level:
    org.springframework.r2dbc.*: DEBUG
