version: '3.8'
services:
  mysql:
    image: mysql:8.0.33
    container_name: serverdriven-mysql
    restart: always
    ports:
      - '33061:3306'
    environment:
      MYSQL_USER: serverdriven
      MYSQL_PASSWORD: serverdriven
      MYSQL_DATABASE: serverdriven
      MYSQL_ROOT_PASSWORD: serverdriven
      TZ: 'Asia/Seoul'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysqldb:/var/lib/mysql

  redis:
    image: redis:6.2.6
    container_name: serverdriven-redis
    command: redis-server --port 6379
    restart: always
    ports:
      - "63792:6379"

volumes:
  mysqldb:
